/**
 * Company career boards to poll directly.
 *
 * Chosen for three reasons: they hire the kinds of roles this index is for,
 * they hire remotely or across borders, and a good share of them are known to
 * sponsor work visas in their home markets.
 *
 * Board tokens change when a company migrates hiring systems, so this list is
 * validated by running `npm run collect -- --probe`, which reports every board
 * that no longer answers. Dead entries are pruned rather than left to waste a
 * request every day.
 */

export const BOARDS = [
  /* ------------------------------------------------------- United States -- */
  { name: 'Stripe', ats: 'greenhouse', token: 'stripe' },
  { name: 'Figma', ats: 'greenhouse', token: 'figma' },
  { name: 'Databricks', ats: 'greenhouse', token: 'databricks' },
  { name: 'Coinbase', ats: 'greenhouse', token: 'coinbase' },
  { name: 'Cloudflare', ats: 'greenhouse', token: 'cloudflare' },
  { name: 'Discord', ats: 'greenhouse', token: 'discord' },
  { name: 'Dropbox', ats: 'greenhouse', token: 'dropbox' },
  { name: 'Reddit', ats: 'greenhouse', token: 'reddit' },
  { name: 'Twilio', ats: 'greenhouse', token: 'twilio' },
  { name: 'Asana', ats: 'greenhouse', token: 'asana' },
  { name: 'Brex', ats: 'greenhouse', token: 'brex' },
  { name: 'MongoDB', ats: 'greenhouse', token: 'mongodb' },
  { name: 'Elastic', ats: 'greenhouse', token: 'elastic' },
  { name: 'Datadog', ats: 'greenhouse', token: 'datadog' },
  { name: 'GitLab', ats: 'greenhouse', token: 'gitlab' },
  { name: 'Pinterest', ats: 'greenhouse', token: 'pinterest' },
  { name: 'Instacart', ats: 'greenhouse', token: 'instacart' },
  { name: 'Flexport', ats: 'greenhouse', token: 'flexport' },
  { name: 'Robinhood', ats: 'greenhouse', token: 'robinhood' },
  { name: 'Affirm', ats: 'greenhouse', token: 'affirm' },
  { name: 'Samsara', ats: 'greenhouse', token: 'samsara' },
  { name: 'HubSpot', ats: 'greenhouse', token: 'hubspot' },
  { name: 'Grafana Labs', ats: 'greenhouse', token: 'grafanalabs' },
  { name: 'Airtable', ats: 'greenhouse', token: 'airtable' },
  { name: 'Webflow', ats: 'greenhouse', token: 'webflow' },
  { name: 'Amplitude', ats: 'greenhouse', token: 'amplitude' },
  { name: 'Okta', ats: 'greenhouse', token: 'okta' },
  { name: 'Fastly', ats: 'greenhouse', token: 'fastly' },
  { name: 'Duolingo', ats: 'greenhouse', token: 'duolingo' },
  { name: 'Udemy', ats: 'greenhouse', token: 'udemy' },
  { name: 'Coursera', ats: 'greenhouse', token: 'coursera' },
  { name: 'Squarespace', ats: 'greenhouse', token: 'squarespace' },

  /* -------------------------------------------------------------- Europe -- */
  { name: 'Adyen', ats: 'greenhouse', token: 'adyen' },
  { name: 'Wise', ats: 'greenhouse', token: 'wise' },
  { name: 'Monzo', ats: 'greenhouse', token: 'monzo' },
  { name: 'N26', ats: 'greenhouse', token: 'n26' },
  { name: 'SumUp', ats: 'greenhouse', token: 'sumup' },
  { name: 'Contentful', ats: 'greenhouse', token: 'contentful' },
  { name: 'GetYourGuide', ats: 'greenhouse', token: 'getyourguide' },
  { name: 'Intercom', ats: 'greenhouse', token: 'intercom' },
  { name: 'Trustpilot', ats: 'greenhouse', token: 'trustpilot' },
  { name: 'Doctolib', ats: 'greenhouse', token: 'doctolib' },

  /* ----------------------------------------------- remote-first employers -- */
  { name: 'Canonical', ats: 'greenhouse', token: 'canonical' },
  { name: 'Palantir', ats: 'lever', token: 'palantir' },
  { name: 'Veeva', ats: 'lever', token: 'veeva' },
  { name: 'Mistral AI', ats: 'lever', token: 'mistral' },

  { name: 'OpenAI', ats: 'ashby', token: 'openai' },
  { name: 'Ramp', ats: 'ashby', token: 'ramp' },
  { name: 'Vercel', ats: 'ashby', token: 'vercel' },
  { name: 'Linear', ats: 'ashby', token: 'linear' },
  { name: 'PostHog', ats: 'ashby', token: 'posthog' },
  { name: 'Replit', ats: 'ashby', token: 'replit' },
  { name: 'Clerk', ats: 'ashby', token: 'clerk' },
  { name: 'Deel', ats: 'ashby', token: 'deel' },
  { name: 'Modal', ats: 'ashby', token: 'modal' },
  { name: 'Baseten', ats: 'ashby', token: 'baseten' },
  /* ---------------------------------------------------------- discovered --
   * Found with `npm run discover`, which derives a likely token from the
   * company name and checks whether the board answers. Ordered by how many
   * junior-looking roles each had at the time, because early-career supply is
   * the scarcest thing in this index.
   */
  { name: 'Wolt', ats: 'greenhouse', token: 'wolt' },
  { name: 'Oscar Health', ats: 'greenhouse', token: 'oscar' },
  { name: 'Ninja Van', ats: 'lever', token: 'ninjavan' },
  { name: 'HelloFresh', ats: 'greenhouse', token: 'hellofresh' },
  { name: 'Celonis', ats: 'greenhouse', token: 'celonis' },
  { name: 'Airwallex', ats: 'ashby', token: 'airwallex' },
  { name: 'Snowflake', ats: 'ashby', token: 'snowflake' },
  { name: 'Cabify', ats: 'greenhouse', token: 'cabify' },
  { name: 'Tamara', ats: 'greenhouse', token: 'tamara' },
  { name: 'Faire', ats: 'greenhouse', token: 'faire' },
  { name: 'Together AI', ats: 'greenhouse', token: 'togetherai' },
  { name: 'Braze', ats: 'greenhouse', token: 'braze' },
  { name: 'Cohere', ats: 'ashby', token: 'cohere' },
  { name: 'Isar Aerospace', ats: 'greenhouse', token: 'isaraerospace' },
  { name: 'Perplexity', ats: 'ashby', token: 'perplexity' },
  { name: 'Zocdoc', ats: 'greenhouse', token: 'zocdoc' },
  { name: 'Gusto', ats: 'greenhouse', token: 'gusto' },
  { name: 'Hightouch', ats: 'greenhouse', token: 'hightouch' },
  { name: 'Mixpanel', ats: 'greenhouse', token: 'mixpanel' },
  { name: 'Raisin', ats: 'greenhouse', token: 'raisin' },
  { name: 'Xendit', ats: 'greenhouse', token: 'xendit' },
  { name: 'Careem', ats: 'greenhouse', token: 'careem' },
  { name: 'Choco', ats: 'ashby', token: 'choco' },
  { name: 'Preply', ats: 'ashby', token: 'preply' },
  { name: 'LangChain', ats: 'ashby', token: 'langchain' },
  { name: 'Trainline', ats: 'ashby', token: 'trainline' },
  { name: 'Iterable', ats: 'greenhouse', token: 'iterable' },
  { name: 'Culture Amp', ats: 'greenhouse', token: 'cultureamp' },
  { name: 'Griffin', ats: 'ashby', token: 'griffin' },
  { name: 'Moniepoint', ats: 'greenhouse', token: 'moniepoint' },
  { name: 'Chainguard', ats: 'greenhouse', token: 'chainguard' },
  { name: 'Deepgram', ats: 'ashby', token: 'deepgram' },
  { name: 'Synthesia', ats: 'ashby', token: 'synthesia' },
  { name: 'Thunes', ats: 'greenhouse', token: 'thunes' },
  { name: 'Nium', ats: 'lever', token: 'nium' },
  { name: 'SafetyCulture', ats: 'ashby', token: 'safetyculture' },
  { name: 'Truecaller', ats: 'greenhouse', token: 'truecaller' },
  { name: 'Roboflow', ats: 'ashby', token: 'roboflow' },
  { name: 'M-KOPA', ats: 'ashby', token: 'm-kopa' },
  { name: 'Lunar', ats: 'ashby', token: 'lunar' },
  { name: 'Zilch', ats: 'ashby', token: 'zilch' },
  { name: 'Trivago', ats: 'greenhouse', token: 'trivago' },
  { name: 'Labelbox', ats: 'greenhouse', token: 'labelbox' },
  { name: 'ElevenLabs', ats: 'ashby', token: 'elevenlabs' },
  { name: 'Fivetran', ats: 'greenhouse', token: 'fivetran' },
  { name: 'ClickHouse', ats: 'greenhouse', token: 'clickhouse' },
  { name: 'Klaviyo', ats: 'greenhouse', token: 'klaviyo' },
  { name: 'Pennylane', ats: 'ashby', token: 'pennylane' },
  { name: 'Nubank', ats: 'ashby', token: 'nubank' },
  { name: '1Password', ats: 'ashby', token: '1password' },
  { name: 'Tailscale', ats: 'greenhouse', token: 'tailscale' },
  { name: 'Mercury', ats: 'greenhouse', token: 'mercury' },
  { name: 'Temporal', ats: 'ashby', token: 'temporal' },
  { name: 'Supabase', ats: 'ashby', token: 'supabase' },
  { name: 'LaunchDarkly', ats: 'greenhouse', token: 'launchdarkly' },
  { name: 'Cognite', ats: 'greenhouse', token: 'cognite' },
  { name: 'Miro', ats: 'ashby', token: 'miro' },
  { name: 'Pendo', ats: 'greenhouse', token: 'pendo' },
  { name: 'Thought Machine', ats: 'ashby', token: 'thought-machine' },
  { name: 'Hopper', ats: 'ashby', token: 'hopper' },
  { name: 'Sentry', ats: 'ashby', token: 'sentry' },
  { name: 'Attentive', ats: 'greenhouse', token: 'attentive' },
  { name: 'Algolia', ats: 'greenhouse', token: 'algolia' },
  { name: 'Render', ats: 'ashby', token: 'render' },
  { name: 'Confluent', ats: 'ashby', token: 'confluent' },
  { name: 'Outreach', ats: 'lever', token: 'outreach' },
  { name: 'Float', ats: 'ashby', token: 'float' },
  { name: 'Astronomer', ats: 'ashby', token: 'astronomer' },
  { name: 'Sanity', ats: 'ashby', token: 'sanity' },
  { name: 'Multiverse', ats: 'ashby', token: 'multiverse' },
  { name: 'Bitwarden', ats: 'greenhouse', token: 'bitwarden' },
  { name: 'Cockroach Labs', ats: 'greenhouse', token: 'cockroachlabs' },
  { name: 'GoCardless', ats: 'greenhouse', token: 'gocardless' },
  { name: 'Oyster', ats: 'ashby', token: 'oyster' },
  { name: 'Gorgias', ats: 'ashby', token: 'gorgias' },
  { name: 'Andela', ats: 'ashby', token: 'andela' },
  { name: 'Honeycomb', ats: 'greenhouse', token: 'honeycomb' },
  { name: 'Pipedrive', ats: 'lever', token: 'pipedrive' },
  { name: 'Anyscale', ats: 'ashby', token: 'anyscale' },
  { name: 'Semgrep', ats: 'ashby', token: 'semgrep' },
  { name: 'Forto', ats: 'ashby', token: 'forto' },
  { name: 'Vay', ats: 'greenhouse', token: 'vay' },
  { name: 'Calendly', ats: 'greenhouse', token: 'calendly' },
  { name: 'Typeform', ats: 'greenhouse', token: 'typeform' },
  { name: 'Zenjob', ats: 'ashby', token: 'zenjob' },
  { name: 'StackBlitz', ats: 'greenhouse', token: 'stackblitz' },
  { name: 'Storyblok', ats: 'greenhouse', token: 'storyblok' },
  { name: 'Help Scout', ats: 'ashby', token: 'helpscout' },
  { name: 'PlanetScale', ats: 'greenhouse', token: 'planetscale' },
  { name: 'Buildkite', ats: 'greenhouse', token: 'buildkite' },
  { name: 'Airbyte', ats: 'ashby', token: 'airbyte' },
  { name: 'Deputy', ats: 'lever', token: 'deputy' },
  { name: 'Zapier', ats: 'ashby', token: 'zapier' },
  { name: 'Mural', ats: 'ashby', token: 'mural' },
  { name: 'Grover', ats: 'greenhouse', token: 'grover' },
  { name: 'Railway', ats: 'ashby', token: 'railway' },
  { name: 'TrueLayer', ats: 'greenhouse', token: 'truelayer' },
  { name: 'Pinecone', ats: 'ashby', token: 'pinecone' },
  { name: 'Skyscanner', ats: 'greenhouse', token: 'skyscanner' },
  { name: 'Modern Treasury', ats: 'ashby', token: 'moderntreasury' },
  { name: 'Form3', ats: 'greenhouse', token: 'form3' },
  { name: 'AssemblyAI', ats: 'greenhouse', token: 'assemblyai' },
  { name: 'Neon', ats: 'ashby', token: 'neon' },
  { name: 'LogRocket', ats: 'lever', token: 'logrocket' },
  { name: 'Close', ats: 'ashby', token: 'close' },
  { name: 'Immutable', ats: 'lever', token: 'immutable' },
  { name: 'CircleCI', ats: 'greenhouse', token: 'circleci' },
  { name: 'Contentstack', ats: 'greenhouse', token: 'contentstack' },
  { name: 'Guild', ats: 'greenhouse', token: 'guild' },
  { name: 'Runway', ats: 'ashby', token: 'runway' },
  { name: 'Brilliant', ats: 'lever', token: 'brilliant' },
  { name: 'Ghost', ats: 'greenhouse', token: 'ghost' },
  { name: 'Doppler', ats: 'ashby', token: 'doppler' },
  { name: 'Cedar', ats: 'ashby', token: 'cedar' },
  { name: 'Buffer', ats: 'ashby', token: 'buffer' },
  { name: 'Chili Piper', ats: 'ashby', token: 'chilipiper' },
  { name: 'Netlify', ats: 'greenhouse', token: 'netlify' },
  { name: 'Prisma', ats: 'greenhouse', token: 'prisma' },
  { name: 'Remote', ats: 'greenhouse', token: 'remote' },
  { name: 'Weaviate', ats: 'ashby', token: 'weaviate' },
  { name: 'Aha', ats: 'greenhouse', token: 'aha' },
]
