/**
 * Downloads the web fonts once and rewrites the CSS to point at local copies,
 * so the running site makes no request to Google.
 *
 * That matters here for three reasons: the site claims no tracking, and a font
 * request still hands a third party the visitor's IP on every page load; the
 * home-screen app should work with no connection at all; and one fewer network
 * dependency is one fewer thing that can fail.
 *
 * Run it when the font list changes:
 *   node scripts/fetch-fonts.mjs
 *
 * Output: public/fonts/*.woff2 and src/fonts.css, both committed.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outDir = path.join(root, 'public/fonts')

/** Only latin and latin-ext. The interface is English, so the rest is dead weight. */
const KEEP_SUBSETS = new Set(['latin', 'latin-ext'])

const FAMILIES = [
  { css: 'Space+Grotesk:wght@600;700', slug: 'space-grotesk' },
  { css: 'Inter:wght@400;500;600', slug: 'inter' },
]

// Asking as a modern browser is what makes Google serve woff2 rather than the
// older formats it falls back to for unknown clients.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

async function get(url, asText = true) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`${res.status} for ${url}`)
  return asText ? res.text() : Buffer.from(await res.arrayBuffer())
}

fs.mkdirSync(outDir, { recursive: true })

const blocks = []
let downloaded = 0
let skipped = 0

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`
  const css = await get(url)
  await sleep(400)

  // Google emits one @font-face per subset, each preceded by a /* subset */
  // comment. The comment is the only place the subset name appears.
  const parts = css.split('/*').slice(1)

  for (const part of parts) {
    const subset = part.slice(0, part.indexOf('*/')).trim()
    const face = part.slice(part.indexOf('*/') + 2)
    if (!/@font-face/.test(face)) continue

    if (!KEEP_SUBSETS.has(subset)) {
      skipped++
      continue
    }

    const src = face.match(/src:\s*url\((https:[^)]+\.woff2)\)/)
    const weight = face.match(/font-weight:\s*([^;]+);/)
    const style = face.match(/font-style:\s*([^;]+);/)
    const family = face.match(/font-family:\s*'([^']+)'/)
    const range = face.match(/unicode-range:\s*([^;]+);/)
    if (!src || !weight || !family) continue

    const file = `${fam.slug}-${weight[1].trim()}-${subset}.woff2`
    const bin = await get(src[1], false)
    fs.writeFileSync(path.join(outDir, file), bin)
    downloaded++
    await sleep(250)

    blocks.push(
      [
        '@font-face {',
        `  font-family: '${family[1]}';`,
        `  font-style: ${style ? style[1].trim() : 'normal'};`,
        `  font-weight: ${weight[1].trim()};`,
        '  font-display: swap;',
        // Resolved against the built stylesheet, which lands in /assets/, so the
        // path has to climb out to the site root. BASE_URL is not available in
        // plain CSS, hence the relative hop.
        `  src: url('../fonts/${file}') format('woff2');`,
        range ? `  unicode-range: ${range[1].trim()};` : null,
        '}',
      ]
        .filter(Boolean)
        .join('\n')
    )

    console.log(`  ${file}  ${(bin.length / 1024).toFixed(1)}kb`)
  }
}

const header = `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
   Self-hosted so the site makes no third-party request. Re-run the script to
   change weights or families. */\n\n`

fs.writeFileSync(path.join(root, 'src/fonts.css'), header + blocks.join('\n\n') + '\n')

const total = fs
  .readdirSync(outDir)
  .filter((f) => f.endsWith('.woff2'))
  .reduce((sum, f) => sum + fs.statSync(path.join(outDir, f)).size, 0)

console.log(`\n  ${downloaded} files kept, ${skipped} non-latin subsets skipped`)
console.log(`  total ${(total / 1024).toFixed(0)}kb in public/fonts`)
console.log('  wrote src/fonts.css')
